### PR TITLE
Pull request for your consideration

### PR DESCRIPTION
**Pull request by pnock**
Thanks for the GEM! We've been using it for our Exact Target integration. 

Feel free to take a look at my modifications:

I added some triggered send support, and also switched 'send_to_exact_target' to http POST instead of GET. In our case, we were starting to generate some long xml parameters and we didn't want to run into size limits for GET.  I'm not completely sure how generic the triggered send xml is, but it works well in our case.  I'm not sure if the different Exact Target Account types affect this.

Additionally, we were seeing some issues trying to register Facebook proxy email addresses with Exact Target, for example app+asdfadsfasdfasdf@proxymail.facebook.com.  It was easier to simply POST this data than trying to properly escape the + in the data.

regards,
Paul Nock

### CODE REVIEW

**Comment by jerrod** [comment]
@pnock: Your version also fixes some issues i am having between the exact_target response class and Rack. Thanks!

**Comment by pnock** [comment]
There's a weird issue when trying to remove a subscriber from an Exact Target list.  The gem looks for the word 'success' in the exact target return XML to figure out return status.  Exact Target mis-spells the word "Successfully" when you try to remove a subscriber - there's a C missing.  So the gem throws an exception, even though the operation succeeds on their end.  This update just works alters the regex in the response handler to allow for it.

**Comment by david-mccullars** [comment]
Thanks for the interest!  My sincere apologies for the tardiness on getting to this pull request.  For some reason the email notifications aren't getting to me from github.  Feel free to email me directly if you aren't getting a response (dmccullars@ePublishing.com).

**Comment by pnock** [comment]
No problem - thanks for the reply!

**Pull request merged**
